spring:
  profiles:
    active: local
  config:
    import: classpath:application-prod.yaml
  mvc:
    log-request-details: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: snugo-server

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://snugo:snugo@snugo-mongo.wafflestudio.com/snugo
logging:
  level:
    root: debug
jwt:
  secret: jwtsecretsnugo101010101010101010101010
